chore: update code owners list
rakutentech/android-inappmessaging pull request #310
Opened 2023-01-27 07:12 UTC by mdusmangani-jp

# Description
Update code owners list

## Links
NA

# Checklist
- [ ] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [ ] I wrote/updated tests for new/changed code
- [ ] I removed all sensitive data **before every commit**, including API endpoints and keys
- [ ] I checked that all possible internal and platform/library exceptions are gracefully handled and **will not** crash the host app
- [ ] I checked for open & known issues (especially crashes) for any newly added platform APIs or libraries
- [ ] I tested non-trivial changes on a real device
- [ ] I added ticket/changes in changelog
- [ ] I ran `./gradlew check` without errors

2023-01-29 22:19 UTC, imaginaris requested changes
@mdusmangani-jp please remove apparition47 (Aaron) as well.

2023-01-30 06:10 UTC, maureenorea-clores approved these changes

2023-01-30 06:33 UTC, leila-gu approved these changes

2023-01-30 11:13 UTC, imaginaris approved these changes

2023-01-31 01:56 UTC, merged