feat: Send deviceId with all API Calls and RAT Events (SDKCF-6575)
rakutentech/android-inappmessaging pull request #356
Opened 2023-06-19 10:39 UTC by puneetksh

1. device_id header in all API calls
2. deviceId key in request body
3. device_id in cp (custom_parameter)

# Description
Describe the changes in this pull request.
Explain your rationale of technical decisions you made (unless discussed before).

## Links
Add public links to github issues, design documents and other relevant resources (e.g. previous discussions, platform/tool documentation etc.)

# Checklist
- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I wrote/updated tests for new/changed code
- [ ] I removed all sensitive data **before every commit**, including API endpoints and keys, and internal links
- [ ] I checked that all possible internal and platform/library exceptions are gracefully handled and **will not** crash the host app
- [ ] I checked for open & known issues (especially crashes) for any newly added platform APIs or libraries
- [ ] I tested non-trivial changes on a real device
- [ ] I added ticket/changes in changelog
- [ ] I ran `./gradlew check` without errors

2023-06-19 21:52 UTC, imaginaris reviewed
@puneetksh 
What about putting device ID in RAT events send from IAM events - ([BaseEvent.kt](https://github.com/rakutentech/android-inappmessaging/blob/master/inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/appevents/BaseEvent.kt#L73))
And also I think you need to update tests in PushPrimerTrackerManagerSpec

2023-06-19 21:52 UTC, imaginaris commented on inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/PushPrimerTrackerManager.kt
> +        params[InAppMessagingConstants.RAT_EVENT_KEY_CP] = mapOf(
Do you need to add `cp` key here? I thought every key from `params` is put into `cp` by RAT SDK

2023-06-20 01:06 UTC, maureenorea-clores requested changes
@puneetksh @imaginaris @Esakkiraja-Pothikannan 
Was it decided whether device Id for RMC will be a new header? Or are we going to use the current device-id field?
If we reuse the same header field and same function to retrieve device Id, a change in device-id processing for RMC affects IAM (and vice versa).

2023-06-20 01:06 UTC, maureenorea-clores commented on inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InAppMessagingConstants.kt
> +    const val RAT_EVENT_KEY_CP = "cp"
Remove

2023-06-20 01:23 UTC, maureenorea-clores commented on inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/ConfigQueryParamsBuilder.kt
> +        "deviceId" to deviceId,
Remove. We want to add in header, not as a query parameter

2023-06-21 08:45 UTC, maureenorea-clores commented on inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/ImpressionManager.kt
> +        params[InAppMessagingConstants.RAT_EVENT_KEY_DEVICE_ID] = HostAppInfoRepository.instance().getDeviceId()
Please remove for now

2023-06-21 08:45 UTC, maureenorea-clores commented on inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/PushPrimerTrackerManager.kt
> +        params[InAppMessagingConstants.RAT_EVENT_KEY_DEVICE_ID] = HostAppInfoRepository.instance().getDeviceId()
Please remove for now

2023-06-22 01:26 UTC, maureenorea-clores approved these changes

2023-06-22 05:32 UTC, merged